FROM golang:1.7
MAINTAINER kylejw1@gmail.com

ENV GOOS=linux
ENV GOARCH=arm
ENV GOARM=7

RUN mkdir -p $GOPATH/src/github.com/coreos && cd $GOPATH/src/github.com/coreos
RUN git clone https://github.com/coreos/etcd.git etcd
RUN cd etcd && ./build 

CMD /bin/bash -C "mv $GOPATH/src/github.com/coreos/etcd/bin/etcd* /out"

