FROM golang:1.7
MAINTAINER kylejw1@gmail.com

ENV GOPATH=/go
ENV GOOS=linux
ENV GOARCH=arm
ENV GOARM=7

WORKDIR /go/src/github.com/coreos

RUN git clone --branch v3.1.4 https://github.com/coreos/etcd.git 

RUN cd etcd && ./build 

CMD /bin/bash -c "cp etcd/bin/etcd /out && cp etcd/bin/etcdctl /out"

