FROM golang:1.7
MAINTAINER kylejw1@gmail.com

ENV GOPATH=/go
ENV GOOS=linux
ENV GOARCH=arm
ENV GOARM=7

WORKDIR /go/src/github.com/coreos

RUN git clone --branch v3.0.15 https://github.com/coreos/etcd.git 

RUN cd etcd && ./build 

RUN cd etcd/bin/arm

CMD /bin/bash -c "cp etcd /out && cp etcdctl /out"

